# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 605838e9a842ade7b20b11f5da056de5eaa190c25fd437c9bfecb62a13366078cf44d2269486ca6bd5be5787c3e5a48f5fe591345ef7b6dac5d9e2daf5fce995

test:
  secret_key_base: 7a4fed12cb25cf2f6a293eac4f518577b3b3c3c3de65401d4d679af4afa9290ef17d7bd09f18a03da44c8e4b01a17d9bf82b6d4ed3de90010ad3c29b077835c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
